#!/bin/bash -l
#SBATCH -D /home/tmkhadil/projects/hopscotch/
#SBATCH -o /home/tmkhadil/projects/hopscotch/slurm-log/findTE-stdout-%j.txt
#SBATCH -e /home/tmkhadil/projects/hopscotch/slurm-log/findTE-stderr-%j.txt
#SBATCH -J findTE
#SBATCH -t 24:00:00
set -e
set -u

# dividing fastq files into many smaller files
./fastq_split -o /home/tmkhadil/projects/hopscotch/fqfiles /home/tmkhadil/projects/hopscotch/maize_genome.fa

#relocaTE options
./relocaTE.pl -t | --te_fasta hopscotch.fa -d | --fq_dir /home/tmkhadil/projects/hopscotch/fqfiles -g | --genome_fasta maize_genome.fa -e | --exper sample_id -o | --outdir relocaTE_ouput -1 | --mate_1_id _p1 -2 | --mate_2_id _p2 -u | --unpaired_id .unpaired -p | --parallel 1 -a | --qsub_array 1 -w | --workingdir /home/tmkhadil/projects/hopscotch -l | --len_cutoff 10 -bm | --blat_minScore 10 -m | --mismatch 0.1 -bt | --blat_tileSize 11 -f | --flanking_seq_len 100 -r 1

or

#relocaTE options
./relocaTE.pl -t hopscotch.fa -d /home/tmkhadil/projects/hopscotch/fqfiles -g maize_genome.fa -e sample_id -o relocaTE_ouput -1 _p1 -2 _p2 -u .unpaired -p 1 -a 1 -w /home/tmkhadil/projects/hopscotch -l 10 -bm 10 -m 0.1 -bt 11 -f 100 -r 1
