#!/bin/bash -l
#SBATCH -D /home/tmkhadil/projects/hopscotch/
#SBATCH -o /home/tmkhadil/projects/hopscotch/slurm-log/jobname-stdout-%j.txt
#SBATCH -e /home/tmkhadil/projects/hopscotch/slurm-log/jobname-stderr-%j.txt
#SBATCH -J jobname
#SBATCH -t 24:00:00
set -e
set -u

