#!/bin/bash -l
#SBATCH -D /home/tmkhadil/projects/Hopscotch/
#SBATCH -o /home/tmkhadil/projects/Hopscotch/slurm-log/download_maize_genome-stdout-%j.txt
#SBATCH -e /home/tmkhadil/projects/Hopscotch/slurm-log/download_maize_genome-stderr-%j.txt
#SBATCH -J download_maize_genome
#SBATCH -t 24:00:00
set -e
set -u

wget ftp://ftp.ensemblgenomes.org/pub/plants/release-33/fasta/zea_mays/dna/Zea_mays.AGPv4.dna.toplevel.fa.gz
#tar -xvzf Zea_mays.AGPv4.dna.toplevel.fa.gz
gunzip Zea_mays.AGPv4.dna.toplevel.fa.gz
