#!/bin/bash -l
#SBATCH -D /home/tmkhadil/projects/Hopscotch/
#SBATCH -o /home/tmkhadil/projects/Hopscotch/slurm-log/download_maize_genome-stdout-%j.txt
#SBATCH -e /home/tmkhadil/projects/Hopscotch/slurm-log/download_maize_genome-stderr-%j.txt
#SBATCH -J download_maize_genome
#SBATCH -t 24:00:00
set -e
set -u

wget ftp://ftp.ensemblgenomes.org/pub/plants/release-33/fasta/zea_mays/dna/Zea_mays.AGPv4.dna.toplevel.fa.gz
#tar -xvzf Zea_mays.AGPv4.dna.toplevel.fa.gz
gunzip Zea_mays.AGPv4.dna.toplevel.fa.gz

###OR

cd /home/tmkhadil/projects/Hopscotch/maize_genome

wget ftp://ftp.ensemblgenomes.org/pub/plants/release-33/fasta/zea_mays/dna/Zea_mays.AGPv4.dna.chromosome.1.fa.gz
tar -xvzf Zea_mays.AGPv4.dna.chromosome.1.fa.gz

wget ftp://ftp.ensemblgenomes.org/pub/plants/release-33/fasta/zea_mays/dna/Zea_mays.AGPv4.dna.chromosome.10.fa.gz
tar -xvzf Zea_mays.AGPv4.dna.chromosome.10.fa.gz

wget ftp://ftp.ensemblgenomes.org/pub/plants/release-33/fasta/zea_mays/dna/Zea_mays.AGPv4.dna.chromosome.2.fa.gz
tar -xvzf Zea_mays.AGPv4.dna.chromosome.2.fa.gz

wget ftp://ftp.ensemblgenomes.org/pub/plants/release-33/fasta/zea_mays/dna/Zea_mays.AGPv4.dna.chromosome.3.fa.gz
tar -xvzf Zea_mays.AGPv4.dna.chromosome.3.fa.gz

wget ftp://ftp.ensemblgenomes.org/pub/plants/release-33/fasta/zea_mays/dna/Zea_mays.AGPv4.dna.chromosome.4.fa.gz
tar -xvzf Zea_mays.AGPv4.dna.chromosome.4.fa.gz

wget ftp://ftp.ensemblgenomes.org/pub/plants/release-33/fasta/zea_mays/dna/Zea_mays.AGPv4.dna.chromosome.5.fa.gz
tar -xvzf Zea_mays.AGPv4.dna.chromosome.5.fa.gz

wget ftp://ftp.ensemblgenomes.org/pub/plants/release-33/fasta/zea_mays/dna/Zea_mays.AGPv4.dna.chromosome.6.fa.gz
tar -xvzf Zea_mays.AGPv4.dna.chromosome.6.fa.gz

wget ftp://ftp.ensemblgenomes.org/pub/plants/release-33/fasta/zea_mays/dna/Zea_mays.AGPv4.dna.chromosome.7.fa.gz
tar -xvzf Zea_mays.AGPv4.dna.chromosome.7.fa.gz

wget ftp://ftp.ensemblgenomes.org/pub/plants/release-33/fasta/zea_mays/dna/Zea_mays.AGPv4.dna.chromosome.8.fa.gz
tar -xvzf Zea_mays.AGPv4.dna.chromosome.8.fa.gz

wget ftp://ftp.ensemblgenomes.org/pub/plants/release-33/fasta/zea_mays/dna/Zea_mays.AGPv4.dna.chromosome.9.fa.gz
tar -xvzf Zea_mays.AGPv4.dna.chromosome.9.fa.gz


### concatenate all the unzipped fastas
cat Zea_mays.AGPv4.dna.chromosome*.fa > Zea_mays.AGPv4.dna.ALLchromosome.fa
### remove all the individual chromosome files
rm Zea_mays.AGPv4.dna.chromosome*.fa
